name: wblib
channels:
  - conda-forge
dependencies:
  - python=3.12
  - aiohttp
  - cartopy
  - cmocean
  - colorama
  - goes2go
  - healpy
  - intake<2
  - intake-xarray
  - ipykernel
  - jupyter
  - jupyter-cache
  - matplotlib
  - numpy
  - nbformat
  - pyyaml
  - rasterio
  - requests
  - seaborn
  - xarray
  - zarr
  - pip
  - pip:
    - easygems
    - orcestra
    - rioxarray
    - -e src/
